In [1]:
import pandas as pd

df = pd.read_csv('binary_benign.csv')
df

,ID0,ID1,ID2,ID3,ID4,ID5,ID6,ID7,ID8,ID9,...,DATA_710,DATA_711,DATA_712,DATA_713,DATA_714,DATA_715,DATA_716,label,category,specific_class
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,BENIGN,BENIGN,BENIGN
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,BENIGN,BENIGN,BENIGN
2,0,0,0,0,0,0,0,1,0,0,...,1,1,1,1,1,1,1,BENIGN,BENIGN,BENIGN
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,BENIGN,BENIGN,BENIGN
4,0,0,0,0,0,0,0,1,1,1,...,0,0,0,0,0,0,0,BENIGN,BENIGN,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1223732,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,BENIGN,BENIGN,BENIGN
1223733,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,BENIGN,BENIGN,BENIGN
1223734,0,0,0,0,0,0,0,1,0,0,...,1,0,1,0,0,0,0,BENIGN,BENIGN,BENIGN
1223735,0,0,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,BENIGN,BENIGN,BENIGN
1223736,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,BENIGN,BENIGN,BENIGN